---
title: "Model ThreeMe Tunisia"
author: "Lucia SEQUEIRA - Bijan VALILOU - Jin WANG"
date: "January 2022"
output:
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  pdf_document:
    citation_package: biblatex
    toc: yes
    number_sections: yes
    toc_depth: 2
    highlight: tango
    latex_engine: lualatex
    keep_tex: yes
subtitle: 'Macroeconomic impacts of National Low-Carbon Strategy for a little country in development : the case of Tunisia'
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot[CO,CE]{Modèle ThreeMe Tunisie}
- \fancyfoot[LE,RO]{\thepage}
bibliography: references.bib
---

\newpage

# Introduction

# Literature review

## Energy and economy framework in Tunisia (Jin)

## Climate policy

### Carbon tax (Jin)

### Energetic subsidy (Bee)

Subsidies are defined by @demoor1997 as *'any measure that keeps prices for consumers below the market level or keeps prices for producers above the market level or that reduces costs for consumers and producers by giving direct or indirect support'*. Energy subsidies are a common policy. Their amount is estimated at \$4.7 trillion in 2015 as pointed out @coady2019, which is equivalent to 6.3 percent of Gross Domestic Product . Energy subsidies are very high and fluctuate depending on the price of the energy products. From the database of the International Energy Agency, we can notice that the fossil fuel subsidies have [fallen by 42 percent between 2019 and 2020](https://www.iea.org/topics/energy-subsidies) due to the fall of fuel prices, but theses prices have rocketed in 2021.

The energy subsidies are very present in in the Middle East, North Africa, Afghanistan and Pakistan region (MENAP). According to @coady2019, MENAP is the fourth region in absolute terms, which subsidized the most energy in 2015. Nevertheless, in relative terms, MENAP is the second, if we take the percent of its GDP. The prevalence of energy subsidies in MENAP can be explained by post-par period. @verme2017 explain that theses energy subsidies were introduced in Middle East and North Africa region (MENA) in order to stabilize prices after the decolonization. These stabilization mechanisms became a social protection system.

### Recycle of gouvernment income for tax (Lucia)

hhqhq test test test test test test le 8 jan

# Methodology

## ThreeME model (Bee)

### A neo-Keynesian Computable General Equilibrium model

### ThreeMe model Tunisia : Adaptation for a little country in development

## Description of scenario

-   describe redistribution

## Choice of evaluation indicators

### Data structure

### Kaya identity (Jin)

The Kaya identity is an identity where the total emission of carbon dioxide can be explained by four product driving forcec as population, Gross Domestic Product (GDP) per capita, enerny intensity over GDP and carbon intensity over energy consumption. It is expressed in the form:

$$ Emission_{CO_2} = POP \times\frac{GDP}{POP} \times \frac{TEC}{GDP} \times \frac{TEM}{TEC}$$

where:

HEAD - POP is global population; - GDP is gross domestic product; - TEC is total energy consumption; - TEM is total emission of carbon dioxide;

And:

-   GDP/POP is GDP per capita describing the economical activities within a period;
-   TEC/GDP is energy intensity;
-   TEM/TEC is carbon intensity;

#### Aggregated level

#### Sectorial level

# Results et discussions

## Comparasion of redistribution (lucia)

-   graphique PIB : grandes tendances des scénarii Taxe carbone, Levée des subventions énergétiques
-   chomage : grandes tendances des scénarii Taxe carbone, Levée des subventions énergétiques
-   émissions : grandes tendances des scénarii Taxe carbone, Levée des subventions énergétiques

## Carbon tax (jin)

Avec/ sans recyclage Focus inter-sectoriel

## Lifting of energy subsidies (bee)

Avec/ sans recyclage Focus inter-sectoriel

## ENR

## SNBC

# Prolongements

## D'autres leviers pour analyser (ouverture)

## L'amélioration du cadre statistique

OUverture : pb du secteur informel non pris en compte par la comptabilité nationale

# Conclusion

# Bibliographie
