% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Model ThreeMe Tunisia},
  pdfauthor={Lucia SEQUEIRA - Bijan VALILOU - Jin WANG},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyfoot[CO,CE]{Modèle ThreeMe Tunisie}
\fancyfoot[LE,RO]{\thepage}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{biblatex}
\addbibresource{references.bib}

\title{Model ThreeMe Tunisia}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Macroeconomic impacts of National Low-Carbon Strategy for a
little country in development : the case of Tunisia}
\author{Lucia SEQUEIRA - Bijan VALILOU - Jin WANG}
\date{January 2022}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{4}
\tableofcontents
}
\newpage

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

\hypertarget{energy-and-economy-framework-in-tunisia}{%
\subsection{Energy and economy framework in
Tunisia}\label{energy-and-economy-framework-in-tunisia}}

Tunisia is one of the northernmost countries in Africa, ranked the most
competitive economy in Africa by World Economy Forum in 2009
\autocite{tunisia2022}. The local economy is largely oriented towards
services, which account for 43\% of GDP in 2019
\autocite{worldbank2020}, including the booming IT and tourism
industries. Agriculture is another key sector of the Tunisian economy,
representing 10.4\% of the GDP and employing 12.7\% of the working
population \autocite{worldbank2020}. Thanks to technical progress of
agricultural sector, Tunisia is one of the most productive countries in
Africa. Tunisia's industry represents 22.7\% of GDP and employs 32.5\%
of the working population in 2020 \autocite{bnpparibas}. The industrial
sectors are mainly export oriented especially for manufacturing, Europe
is the destination for more than 75\% of Tunisia's exports
\autocite{worldbank2020}.

Since the Jasmine Revolution on 2011, Tunisia economy has been suffered
from the extended recession. The sanitary crisis on 2020 has worsened
the already precarious situation. Actually, even before COVID-19
Tunisia's capacity for economic resilience had been drained by years of
indecisive public policy-making and growing protectionism
\autocite{worldbank}. In early September 2020, the Tunisian parliament
finally reversed a government of Tenchnocrats in an attempt to remedy
the country's economic situation \autocite{bnpparibas}.

Along with the sluggish economy is the huge energy deficit in Tunisia.
\textcite{irena2021} reported that energy deficit (50\% in 2019) has
existed in Tunisia over the past two decades, mainly because of the
increasing consumption but with the stagnated even declined domestic
production in recent years. \textcite{giz} reported that Tunisia depends
for 60\% on energy imports, and this number is continuously raising. The
energy transition project proclaimed in 2014 aims to reduce energy needs
by 34\% by 2030, lower subsidies and establish incentive mechanisms
favoring profitable and climate friendly investments. However, the
challenging is the lack of reliable institutional mechanisms and
motivation for enterprises to participate, accompanied with a poorly
established service market and weak transmission of knowledge to
citizens, especially outside urban area.

The welfare system is based on non-targeted subsidies. According to
\textcite{albertin2014}, the subsidy policy is a pillar of the Tunisian
welfare system. Targeted social assistance programs are above the
regional average. In 2016, social expenditure represented 3.2 percent of
GDP, majority of which was energy and food subsidies
\autocite{tunisia2020}. In 2021, the fossil fuel subsidies amounted to
\$1,14 billion (2.7\% of GDP) \autocite{trésor2021}. Concerning energy
subsidies, the government subsidizes liquefied petroleum gas (LPG),
natural gas, kerosene, diesel, gasoline, electricity and heavy fuel oil.
The effective subsidies by product are represented in figure X. The LPG
and the electricity subsidies are the main expenditure items as shown in
figure X. A significant part of the energy subsidies are captured by the
wealthiest quintile of the population. On the contrary, in 2013, the
bottom 40\% of the distribution captured only 29\% of energy subsidies
\autocite{worldbank2014}. According to \textcite{cuesta2017} , energy
subsidies are also a cornerstone of the development of Tunisian
productive sectors. The subsidy system allows firms to buy cheap energy
resources. The noncompetitive companies, which employ unskilled workers,
rely on the subsidies.

After the revolution, fiscal and equity issues incited the Tunisian
government to reduce energy subsidies. In 2012, the prices of gasoline,
diesel and electricity increased by 7\% \autocite{albertin2014}. In
2014, energy subsidies to cement firms were reduced by half. In 2020,
Tunisia has introduced an automatic monthly price adjustment mechanism
for petrol and diesel sales, with the aim of eliminating fuel subsidies.

\includegraphics{Images/Composition of fuel subsidies by product.jpg}

Fig.X : Composition of fuel subsidies product (source :
\textcite{tunisia2020})

\includegraphics{Images/Energy subsdies received by welfare quintile.jpg}

Fig.X : Energy subsidies received by welfare quintile, 2015/16 (TND
millions) (source : \textcite{tunisia2020})

\hypertarget{literature-review-in-climate-policy}{%
\subsection{Literature review in climate
policy}\label{literature-review-in-climate-policy}}

\hypertarget{carbon-tax}{%
\subsubsection{Carbon tax}\label{carbon-tax}}

After some reversals over the past twenty years, carbon pricing is
reemerging. Since 2016, many new carbon-pricing initiatives have been
implemented, with several countries considering implementing carbon
pricing in the years ahead, after having signed the Paris Agreement
\autocite{klenert2018}. The level of the carbon price retained, i.e.~the
rate of the tax, corresponds in someway to the value that society places
on the protection of the environment from the consequences of a rise in
temperature \autocite{deperthuis2010}.

When considering the externality associated with the release of CO2 from
combustion, we observe that there is a marginal social cost that exceeds
marginal private cost. The difference between this two costs reflects
the marginal external cost of damage \autocite{goulder2013}. Carbon tax
is the instrument that comes reflect marginal external damage. The
advantage of using a tax system to price environmental harm is to send a
clear price signal to guide economic entities spontaneously to reduce
their level of pollution until their marginal cost of depollution equals
the tax, as pointed by \textcite{deperthuis2010} .

In a competitive market, this will cause private costs to rise and this
will cause an issue of acceptability.

\hypertarget{energy-subsidy}{%
\subsubsection{Energy subsidy}\label{energy-subsidy}}

Subsidies are defined by \textcite{demoor1997} as \emph{`any measure
that keeps prices for consumers below the market level or keeps prices
for producers above the market level or that reduces costs for consumers
and producers by giving direct or indirect support'}. Energy subsidies
are a common policy. Their amount is estimated at \$4.7 trillion in 2015
as pointed out \textcite{coady2019}, which is equivalent to 6.3 percent
of Gross Domestic Product . Energy subsidies fluctuate depending on the
price of the energy products. From the database of the International
Energy Agency, we can notice that the fossil fuel subsidies have
\href{https://www.iea.org/topics/energy-subsidies}{fallen by 42 percent
between 2019 and 2020} due to the drop of fuel prices.

The energy subsidies are very present in the Middle East, North Africa,
Afghanistan and Pakistan region (MENAP). According to
\textcite{coady2019}, MENAP is the fourth region in absolute terms,
which subsidized the most energy in 2015. Nevertheless, in relative
terms, MENAP is the second, if we take into account the percent of its
GDP. The prevalence of energy subsidies in MENAP can be explained by the
post-par period. These energy subsidies were introduced, after the
decolonization, in Middle East and North Africa region (MENA) in order
to stabilize prices and then, became a social protection system
\autocite{verme2017}.

\textcite{fattouh2013} emphasize three positive aspects of the energy
subsidies that we saw above :

\begin{itemize}
\item
  The energy subsidies enhance the incomes of the poorest part of the
  population. It constitute a core part of the welfare system in the
  MENA.
\item
  The energy subsidies help to reduce production costs and to strengthen
  competitiveness of local firms. Energy subsidies are a tool for
  industrialization and diversification policy.
\item
  The regulation of energy prices is used to control inflation and
  stabilize prices.
\end{itemize}

Reducing energy subsidies may improve economic welfare and reduce
emissions \autocites[ ]{aldy2013}[ ]{coady2019}{hahn2021}.
\textcite{fattouh2013} also highlight unintended consequences of energy
subsidies :

\begin{itemize}
\tightlist
\item
  Energy subsidies raise energy intensity of GDP and reduce energy
  efficiency rates. Low energy pricing favors the growth of
  energy-intensive industries and discourage the firms from minimizing
  energy costs. Fig. X below shows that many energy-intensive countries
  have also high fossil fuel subsidies as a proportion of their GDP.
\item
  Energy subsidies distort consumption. Indeed, they cause a fast growth
  in consumption of primary fuels and electricity. According to
  \textcite{fattouh2013}, between 1980 to 2008, the total energy
  consumption in MENA grew more than 5\% annually.
\item
  Energy subsidies distort investments. The weak implementation of
  subsidies provoke underinvestment in energy sectors, where the
  subsidies do not entirely compensate the energy companies. Therefore,
  end users receive a low quality service.
\item
  Energy subsides cause fuel shortages because of low prices. The
  smuggling across borders is also favored by the price differences
  between countries.
\item
  Non-targeted subsidies create inequities between social groups (see
  fig.~X. above).
\end{itemize}

\includegraphics{Images/Subsidies - energy intensity.jpg}

Fig.X : Energy subsidies and energy intensities by country in 2017 (data
: SDG indicators for United Nations Economic Commission for Europe)

\hypertarget{carbon-tax-revenue-recycling-and-double-dividend}{%
\subsubsection{\texorpdfstring{Carbon tax revenue recycling
\underline{and double
dividend}}{Carbon tax revenue recycling and double dividend}}\label{carbon-tax-revenue-recycling-and-double-dividend}}

Tax redistribution is the mechanism that allows the government to return
to the private economy the revenues that are produced by the instrument
\autocite{goulder}. There are many ways in which this redistribution can
operate. Most of the times, the redistribution is presented as a
lump-sum transfer to households and firms, or as a reduction in taxes
that introduce a deformation into the economy as it is the case of labor
taxes. \textcite{klenert2018} findings suggest that lump-sum transfers
are more stable over time, particularly in countries that are stuck in
issues of economic inequality, political distrust and polarization.

Fig.X : Decision-tree diagram for carbon revenue recycling (Source :
\textcite{klenert2018} )

\hypertarget{methodology}{%
\section{Methodology}\label{methodology}}

\hypertarget{threeme-model}{%
\subsection{ThreeME model}\label{threeme-model}}

The ThreeME model is a hybrid neo-Keynesian Computable General
Equilibrium model (1), which had to be adaptated and calibrated on
Tunisian data (2).

\hypertarget{a-hybrid-neo-keynesian-computable-general-equilibrium-model}{%
\subsubsection{A hybrid neo-Keynesian Computable General Equilibrium
model}\label{a-hybrid-neo-keynesian-computable-general-equilibrium-model}}

The \href{https://github.com/fosem/ThreeME_V3-open}{open source} ThreeME
model has been developped since 2008 by OFCE (French Economic
Observatory), ADEME (French Environment and Energy Management Agency)
and NEO (Netherlands Economic Observatory). ThreeME is a Computable
General Equilibrium Model (CGEM), with neo-Keynesian features and a
hybrid structure.

ThreeME combines several features \autocites[
]{callonnec2013}{callonnec2021} :

\begin{itemize}
\tightlist
\item
  ThreeME is a Computable General Equilibrium Model (CGEM), which takes
  into account the interactions and feedbacks between supply and demand
  (see Fig.X). Demand defines supply and in return, supply determines
  demand through the production factor incomes.
\end{itemize}

\includegraphics{Images/Architecture of a CGEM.jpg}

Fig.X : Architecture of CGEM (source : \textcite{callonnec2013})

\begin{itemize}
\item
  ThreeME is a CGEM of neo-Keynesian inspiration. ThreeME differs from
  Walrasian CGEM in its dynamics and its transition to the long run.
  Instead of perfect flexibility hypothesis, prices and quantities
  slowly adjust, because of uncertainties, adjustment costs or temporal
  boundaries. Prices do not clear supply and demands and market
  imperfections are also included in the model. Consequently, there are
  disequilibrium between supply and demand. For instance, involuntary
  unemployment is possible.
\item
  The high sectoral disaggregation is a way to describe the transfers of
  activity from a sector to another. The ThreeME model allows to track
  sectoral changes in investment, employment or energy consumption.
\item
  ThreeME is a hybrid model which combines top-down and bottom-up
  modelling. On one side, the general equilibrium effets are
  represented. On the other side, the energy disaggregation allows for
  the analysis of the energy production and consumption. The trade-offs
  between energy and other production factors and between several energy
  consumptions are included in the model.
\end{itemize}

\hypertarget{threeme-model-tunisia-adaptation-for-a-little-country-in-development}{%
\subsubsection{ThreeMe model Tunisia : Adaptation for a little country
in
development}\label{threeme-model-tunisia-adaptation-for-a-little-country-in-development}}

ThreeME has already been adapted to Mexico by \textcite{landarivera2016}
and to Indonesia by \textcite{reynes2017}. The adaptation of ThreeME to
Tunisia has been founded on consultation with Tunisian experts and other
stakeholders. Indeed, the sectoral disaggregation was validated by
Tunisian stakeholders. At the end, 21 sectors and 18 products were
chosen (see Fig.X). The tax structure is based on the supply and use
table (SUT) of the national accounts.

\includegraphics{Images/Sectoral disaggregation.jpg}

Fig.X : Sectoral disaggregation

The required data are economic data from national accounts, in
particular from Input-Output Tables (IOTs), physical data from energy
balance and detailed tax data by product. These data were collected from
Tunisian institutions, in particular ANME (National Agency for Energy
Management), INS (National Institute of statistics), ONE (National
Energy Observatory), STEG (Tunisian Company of Electricity and Gas),
ITCEQ (Tunisian Institute of Competitiveness and Quantitative Studies),
Ministry of Energy, Mines and Energy Transition and the Ministry of
Economic Development, Investment and International Cooperation.

\hypertarget{description-of-scenarios}{%
\subsection{Description of scenarios}\label{description-of-scenarios}}

We work on six different scenarios that simulate the implementation of
six alternative environmental policies. For both policies carbon tax and
fossil fuels subsidies removal, there are two scenarios. The first one
assuming there is no recycling of revenues and the second one
considering some type of recycling of revenues.

\begin{itemize}
\item
  Scenario 1 : Implementation of a carbon tax from 2021 without
  redistribution of the revenues of the tax in the economy - they are
  used to reduce public debt.
\item
  Scenario 2 : Carbon tax with recycling of revenues that are redirected
  to the Energy Transition Fund. In fact, a part is given back to
  households and a portion is devoted to ``non-polluting'' businesses.
\item
  Scenario 3 : Fossil fuels subsidies removal (without recycling).
\item
  Scenario 4 : Fossil fuels subsidies removal (with recycling). A part
  is given back to households and a portion is given to enterprises in
  proportion to the employment of each sector in the total salaried
  labor force.
\item
  Scenario 5 : Significant penetration of Renewable Energies in the
  electrical mix (80\% by 2050)
\item
  Scenario 6 : Combination of scenarios 2, 4 and 5.
\end{itemize}

\hypertarget{carbon-tax-evolution}{%
\subsubsection{Carbon tax evolution}\label{carbon-tax-evolution}}

Before 2030, carbon tax level is calculated to cover 100\% of the needs
of the Energy Transition Fund, and it raises from 1.1 to 9 DT/tCO2 in 10
years. After 2030, the path of the carbon tax is defined in order to
achieve the emission reduction objectives for 2050. According to the
substitution assumptions retained in ThreeME, achieving an emissions
reduction factor of 5 by 2050 (in relation to 2020) requires an increase
from 9 DT/tCO2 to 372 DT/tCO2 in the carbon tax. In addition to the
carbon tax, price signals have been introduced in order to achieve
energy consumption targets by source.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-6-1} \end{center}

\hypertarget{fossil-fuels-subsidies-removal-over-time}{%
\subsubsection{Fossil fuels subsidies removal over
time}\label{fossil-fuels-subsidies-removal-over-time}}

Changes in fossil fuels subsidies between 2015 and 2020 are due to
fluctuations in energy prices, and the data correspond to observations.
Then from 2020, the removal of subsidies is implemented gradually until
reaching zero subsidies in 2024.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-7-1} \end{center}

\hypertarget{choice-of-evaluation-indicators}{%
\subsection{Choice of evaluation
indicators}\label{choice-of-evaluation-indicators}}

\hypertarget{data-structure}{%
\subsubsection{Data structure}\label{data-structure}}

The analysed data are derived from outputs of model ThreeME Tunisia. All
the indicators are simulated from 2015 to 2050, generating a database
with time series. The indicators used in the analysis if not
exceptionally mentioned are in percentage relative form, meaning the
proportional variation to Baseline scenario:

\[ X = \frac{X_{Shock}}{X_{Baseline}} \times 100\% \tag{1}\] where:

\begin{itemize}
\tightlist
\item
  \(X\) is the indicator used for analysis;
\item
  \(X_{Shock}\) is the model output with different policy scenarios;
\item
  \(X_{Baseline}\) is the model output with baseline scenario;
\end{itemize}

\hypertarget{kaya-identity}{%
\subsubsection{Kaya identity}\label{kaya-identity}}

The Kaya identity, firstly proposed by \autocite{kaya1989}, is an
identity where the total emission of carbon dioxide can be explained by
four product driving forces as population, Gross Domestic Product (GDP)
per capita, enerny intensity over GDP and carbon intensity over energy
consumption \autocite{kayaide2021}. It is expressed in the form:

\[ C = POP \cdot \frac{GDP}{POP} \cdot \frac{TEC}{GDP} \cdot \frac{C}{TEC} \tag{1}\]

where:

\begin{itemize}
\tightlist
\item
  POP is global population;
\item
  GDP is gross domestic product;
\item
  TEC is total energy consumption;
\item
  C is total emission of carbon dioxide;
\end{itemize}

And:

\begin{itemize}
\tightlist
\item
  GDP/POP is GDP per capita describing the economical activities within
  a period;
\item
  TEC/GDP is energy intensity;
\item
  C/TEC is carbon intensity;
\end{itemize}

In this study, we introduced an extension of Kaya identity to explain
how different driving forces influenced the total emission for different
scenarios. Firstly, a extended Kaya identity is used to analysis
CO\textsubscript{2} emission with the aggregated factors, then we couple
with Logarithmic Mean Divisia Index (LMDI) method to decomposite
CO\textsubscript{2} emission at the sectorial level.

We modified the function of Kaya identity mentioned above to adapt our
model assumption, where we integrated a new driving force, named economy
structure, to decomposite emissions driving force at sectorial level.
The five economic sectors considered in ThreeME Tunisia model are:
Industry and Agriculture, Service, Transportation, Energy Transformation
and Electricity. However, we did not take population into consideration
because its increasing rate remains still over time for all our
scenarios and is considered as an exogenous variable in ThreeME model.

Therefore, the CO\textsubscript{2} emission can be written as:

\[  C_{tot} = \Sigma C_{i} = \Sigma( VA \cdot \frac{VA_{i}}{VA} \cdot \frac{EC_{i}}{VA_{i}} \cdot \frac{CE_{i}}{EC_{i}} )=  \Sigma( V \cdot S_{i} \cdot E_{i} \cdot I_{i}) \tag{2}\]
where C\textsubscript{tot} is overall CO\textsubscript{2} emission,
C\textsubscript{i} is CO\textsubscript{2} emission of economic sector i,
VA is total added value, VA\textsubscript{i} is added value of sector i,
EC\textsubscript{i} is total energy consumption by sector i,
CE\textsubscript{i} is CO\textsubscript{2} emission arising from sector
i. According to equation 8, total CO\textsubscript{2} emission can be
explained by four driving forces, including one aggregated indicator,
overall economic activities V, and three sectorial indicators, share of
total added value of sector i S\textsubscript{i}, energy intensity over
added value of sector i E\textsubscript{i} and carbon intensity over
energy consumption of sector i I\textsubscript{i}. Especially,
S\textsubscript{i} can be interpreted as economy structure of Tunisia,
\textcite{grubb2015} and \textcite{kanitkar2015} found that for a
developing country, this term could be a key variable determining the
future emissions pathway.

The effects of driving forces can be expressed in two ways:
multiplicative and additive form, where multiplicative deviation
\(D_{tot}\) is the ratio of total CO\textsubscript{2} emission between
policy scenario and baseline scenario (equation 3), and additive
deviation \(\Delta C_{tot}\) is the difference of total
CO\textsubscript{2} emission (equation 4). The two expressions are shown
below:

\[ D_{tot} =\frac{C_{2}}{C_{0}} = \Pi(\frac{V_{2}}{V_{0}} \cdot \frac{S_{2,i}}{S_{0,i}} \cdot \frac{E_{2,i}}{E_{0,i}}  \cdot \frac{I_{2,i}}{I_{0,i}}) = D_{V}  \cdot  D_{S} \cdot D_{E} \cdot D_{I} = D_{V}  \cdot \Pi ( D_{S_{i}} \cdot D_{E_{i}} \cdot D_{I_{i}}) \tag{3}\]

\[ \Delta C_{tot} = C_{2} - C_{0} = \Delta C_{V} + \Delta C_{S} + \Delta C_{E} + \Delta C_{I} = \Delta C_{V} + \Sigma( \Delta C_{S_{i}} + \Delta C_{E_{i}} + \Delta C_{I_{i}}) \tag{4}\]
where subscript \(tot\) represents overall change of emission, subscript
0 and 2 mean baseline scenario and policy scenario respectively. Hence
we obtain the index \(D_{V}\), \(D_{S}\), \(D_{E}\) and \(D_{I}\),
meaning the deviation of emissions due to change of overall economic
activities, economy structure, energy intensity and carbon intensity,
while \(\Delta C_{V}\), \(\Delta C_{S}\), \(\Delta C_{E}\) and
\(\Delta C_{I}\) depict the difference of emissions related to change of
driving forces.

Now we expect to identify the effect of each driving force at a
sectorial level, to do this, we used a LMDI method proposed by
\textcite{ang1997} and \textcite{ang2005}. For multiplicative form, we
have:

\[ D_{X} = exp ( \Sigma \frac{(C_{2,i}-C_{0,i})/(lnC_{2,i}-lnC_{0,i})}{(C_{2}-C_{0})/(lnC_{2}-lnC_{0})} \cdot ln \frac{X_{2,(i)}}{X_{0,(i)}} ) \tag{11}\]
\[ \Delta C_{X} =  \Sigma (\frac{C_{2,i}-C_{0,i}}{lnC_{2,i}-lnC_{0,i}} \cdot ln\frac{X_{2,(i)}}{X_{0,(i)}}) \tag{12} \]
where \(C_{2}\) is total emission of policy scenario, \(C_{0}\) is total
emission of baseline, \(C_{2,i}\) is emission of policy scenario arising
from sector i, \(C_{0,i}\) is emission of baseline arising from sector
i, \(D_{X}\) and \(\Delta C_{X}\) represent multiplicative and additive
index of driving force \(X\), \(X_{2,(i)}\) is value of driving force
\(X\) of policy scenario for sector i, \(X_{0,(i)}\) is value of driving
force \(X\) of baseline for sector i.

It should be noted that we integrated the energy consumption and carbon
dioxide emission by household into that of energy transformation sector.
On the one hand, household is the aggregation who does not hold added
value, but who, at meantime, does contribute to the overall CO2
emissions, however, the emissions arose by households are certainly not
negligible. On the other hand, the households consume principally fuels,
natural gas and electricity, where the first two are derived from energy
transformation sector. As for electricity, the usage of electricity in
fact does not arise any emissions according to the assumptions for it is
taken into consideration during its generation i.e.~electricity sector.
This may not be the best solution, however, it does not change our
principal results but largely simplify the data treatment process. So we
consider, for the following analysis, that for energy transformation
sector the consumption of fuels for transportation, fuels for other uses
and electricity are derived from households, whilst the natural gas
consumption belongs to the sector itself.

\hypertarget{results-and-discussions}{%
\section{Results and discussions}\label{results-and-discussions}}

In this section we will analyse the results obtained for the different
scenarios for the different variables taken into account.

\hypertarget{importance-of-redistribution}{%
\subsection{Importance of
redistribution}\label{importance-of-redistribution}}

In this section we will analyse the influence of the redistribution of
both the carbon tax and the removed energy subsidies. We will observe
the impact of the redistribution on both the economical and on the
environmental aspect. We will focus on GDP and employment variations
among other indicators when it comes to the economical aspect and we
will analyse the evolution of CO2 emissions for the environmental
aspect.

\hypertarget{carbon-tax-with-and-without-redistribution}{%
\subsubsection{Carbon tax with and without
redistribution}\label{carbon-tax-with-and-without-redistribution}}

We first analyse the redistribution of the carbon tax. The figure below
shows the variation in GDP in relation to the baseline for both
scenarios carbon tax with and without redistribution. We observe that
the scenario with redistribution shows a marked increase in GDP since
2030 (+2\% in 2050 in relation to the baseline) while GDP decreases for
the scenario without redistribution (-1.5\% in 2050 in comparison with
the baseline). The variations in GDP observed before 2030 are less
pronounced, and that correspond to the progressive implementation of the
carbon tax.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-8-1} \end{center}

If we analyse employment variations, we can see that the redistribution
operates an increase on it in relation to the baseline (+2.3\% in 2050).
In the scenario without redistribution there is a decrease in the level
of employment in comparison with the baseline (-1\% in 2050).

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-9-1} \end{center}

Regarding CO2 emissions, it is noted that there is not a great
difference in the variation between the scenarios carbon tax with and
without redistribution. However, we can notice that the reduction in
emissions compared to the baseline is slightly larger in the case that
there is no redistribution, and this seems consistent with the economic
recession observed before.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-10-1} \end{center}

\hypertarget{fossil-fuels-subsidies-removal-with-and-without-redistribution}{%
\subsubsection{Fossil fuels subsidies removal with and without
redistribution}\label{fossil-fuels-subsidies-removal-with-and-without-redistribution}}

If we do the same analyse on the economic indicators for the scenarios
subsidies removal with and without redistribution, we notice that in
general lines trends are similar.

In the case of GDP variation for the scenario with redistribution, we
can see in the figure below that there is a maximum increase of
approximately 0.5\% around the year 2024 when the subsidies fall to
zero. Then there is an stabilization in GDP around baseline levels. For
the scenario subsidies removal without redistribution, there is a strong
decrease in GDP variation around 2028 (-2.1\% in relation to the
baseline), and then a progressive increase. However, GDP variation is
always negative in comparison to the baseline at least in the period
2020-2050.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-11-1} \end{center}

As regards employment, the scenario with redistribution presents a
positive variation in relation to the baseline for the period 2020-2030,
and then a negative one between 2030 and 2045. This variation is in
absolute terms always below 0.5\%. If we consider the scenario without
redistribution we observe a negative variation that goes beyond -2.5\%
around 2030.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-12-1} \end{center}

There are no marked differencies in emissions variation in relation with
the baseline between the two scenarios (fossil fuels subsidies removal
with and without redistribution). The variation in emissions goes beyond
25\% for the scenario without redistribution while it remains below 25\%
for the scenario with redistribution. As in the case of the carbon tax,
the economic recession could explain this difference.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-13-1} \end{center}

If we observe the variation in the gross salary, we can notice that in
the case of carbon tax there is no difference between the scenarios with
or without redistribution for this indicator while for the case of
fossil fuels subsidies removal, we can observe that the scenario without
redistribution presents a higher variation in relation to the baseline.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-14-1} \end{center}

Tableau Taxe sans redistribution

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-15}Macroeconomic impacts of Carbon tax scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
\cellcolor{gray!6}{GDP in volume} & \cellcolor{gray!6}{0.00} & \cellcolor{gray!6}{-0.05} & \cellcolor{gray!6}{-0.07} & \cellcolor{gray!6}{-0.43} & \cellcolor{gray!6}{-0.95} & \cellcolor{gray!6}{-1.28} & \cellcolor{gray!6}{-1.47}\\
Household consumption & -0.05 & -0.15 & -0.18 & -1.54 & -2.39 & -2.21 & -1.62\\
\cellcolor{gray!6}{Investment} & \cellcolor{gray!6}{0.00} & \cellcolor{gray!6}{-0.09} & \cellcolor{gray!6}{-0.15} & \cellcolor{gray!6}{-0.68} & \cellcolor{gray!6}{-1.28} & \cellcolor{gray!6}{-0.96} & \cellcolor{gray!6}{0.00}\\
Exports & 0.00 & -0.05 & -0.13 & -0.56 & -1.57 & -2.79 & -3.88\\
\cellcolor{gray!6}{Imports} & \cellcolor{gray!6}{-0.06} & \cellcolor{gray!6}{-0.18} & \cellcolor{gray!6}{-0.25} & \cellcolor{gray!6}{-1.81} & \cellcolor{gray!6}{-2.97} & \cellcolor{gray!6}{-2.92} & \cellcolor{gray!6}{-2.18}\\
Household disposable income & -0.07 & -0.15 & -0.18 & -1.59 & -2.35 & -2.17 & -1.62\\
\cellcolor{gray!6}{Household consumption price index} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.22} & \cellcolor{gray!6}{0.38} & \cellcolor{gray!6}{2.39} & \cellcolor{gray!6}{5.28} & \cellcolor{gray!6}{8.17} & \cellcolor{gray!6}{10.58}\\
production price index & 0.05 & 0.23 & 0.41 & 2.51 & 5.94 & 9.57 & 12.65\\
\cellcolor{gray!6}{Added value price index} & \cellcolor{gray!6}{-0.04} & \cellcolor{gray!6}{0.10} & \cellcolor{gray!6}{0.28} & \cellcolor{gray!6}{1.00} & \cellcolor{gray!6}{4.01} & \cellcolor{gray!6}{7.80} & \cellcolor{gray!6}{11.33}\\
Intermediate consumption price index & 0.14 & 0.37 & 0.55 & 4.17 & 8.12 & 11.58 & 14.13\\
\cellcolor{gray!6}{Export price index} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{0.14} & \cellcolor{gray!6}{0.27} & \cellcolor{gray!6}{1.52} & \cellcolor{gray!6}{3.67} & \cellcolor{gray!6}{5.93} & \cellcolor{gray!6}{7.82}\\
Import price index & -0.01 & -0.10 & -0.12 & -0.63 & -0.81 & -0.90 & -1.00\\
\cellcolor{gray!6}{Gross nominal wage} & \cellcolor{gray!6}{0.00} & \cellcolor{gray!6}{0.11} & \cellcolor{gray!6}{0.27} & \cellcolor{gray!6}{1.09} & \cellcolor{gray!6}{3.42} & \cellcolor{gray!6}{6.35} & \cellcolor{gray!6}{9.06}\\
Real cost of labor & 0.04 & 0.01 & -0.01 & 0.08 & -0.57 & -1.36 & -2.06\\
\cellcolor{gray!6}{Wage employment rate (in thousands)} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{-1.67} & \cellcolor{gray!6}{-4.01} & \cellcolor{gray!6}{-13.17} & \cellcolor{gray!6}{-35.88} & \cellcolor{gray!6}{-45.85} & \cellcolor{gray!6}{-43.00}\\
Unemployment rate (in point) & 0.00 & 0.03 & 0.06 & 0.20 & 0.50 & 0.62 & 0.56\\
\cellcolor{gray!6}{Trade balance (in point of GDP)} & \cellcolor{gray!6}{0.05} & \cellcolor{gray!6}{0.25} & \cellcolor{gray!6}{0.35} & \cellcolor{gray!6}{1.96} & \cellcolor{gray!6}{3.09} & \cellcolor{gray!6}{3.44} & \cellcolor{gray!6}{3.39}\\
Public budget balance (in points of GDP) & 0.09 & 0.22 & 0.31 & 1.86 & 2.72 & 3.26 & 3.49\\
\cellcolor{gray!6}{Public debt (in points of GDP)} & \cellcolor{gray!6}{-0.13} & \cellcolor{gray!6}{-0.89} & \cellcolor{gray!6}{-2.06} & \cellcolor{gray!6}{-8.68} & \cellcolor{gray!6}{-18.39} & \cellcolor{gray!6}{-29.00} & \cellcolor{gray!6}{-39.20}\\
CO2 emissions & -0.64 & -2.22 & -3.20 & -18.53 & -31.99 & -40.42 & -45.67\\
\bottomrule
\end{tabu}
\end{table}

Tableau Taxe avec redistribution

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-16}Macroeconomic impacts of Carbon tax scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
\cellcolor{gray!6}{GDP in volume} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{0.11} & \cellcolor{gray!6}{0.13} & \cellcolor{gray!6}{0.97} & \cellcolor{gray!6}{1.56} & \cellcolor{gray!6}{1.87} & \cellcolor{gray!6}{1.93}\\
Household consumption & 0.02 & 0.13 & 0.20 & 1.04 & 2.12 & 3.29 & 4.20\\
\cellcolor{gray!6}{Investment} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.10} & \cellcolor{gray!6}{0.74} & \cellcolor{gray!6}{1.47} & \cellcolor{gray!6}{2.62} & \cellcolor{gray!6}{3.96}\\
Exports & 0.00 & -0.03 & -0.09 & -0.36 & -1.20 & -2.32 & -3.36\\
\cellcolor{gray!6}{Imports} & \cellcolor{gray!6}{-0.03} & \cellcolor{gray!6}{-0.02} & \cellcolor{gray!6}{-0.03} & \cellcolor{gray!6}{-0.40} & \cellcolor{gray!6}{-0.44} & \cellcolor{gray!6}{0.20} & \cellcolor{gray!6}{1.13}\\
Household disposable income & 0.03 & 0.14 & 0.19 & 1.07 & 2.12 & 3.27 & 4.17\\
\cellcolor{gray!6}{Household consumption price index} & \cellcolor{gray!6}{0.05} & \cellcolor{gray!6}{0.17} & \cellcolor{gray!6}{0.33} & \cellcolor{gray!6}{1.89} & \cellcolor{gray!6}{4.51} & \cellcolor{gray!6}{7.24} & \cellcolor{gray!6}{9.49}\\
production price index & 0.03 & 0.17 & 0.35 & 1.88 & 4.99 & 8.43 & 11.33\\
\cellcolor{gray!6}{Added value price index} & \cellcolor{gray!6}{-0.07} & \cellcolor{gray!6}{0.02} & \cellcolor{gray!6}{0.19} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{2.84} & \cellcolor{gray!6}{6.42} & \cellcolor{gray!6}{9.76}\\
Intermediate consumption price index & 0.13 & 0.33 & 0.51 & 3.70 & 7.42 & 10.73 & 13.14\\
\cellcolor{gray!6}{Export price index} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.09} & \cellcolor{gray!6}{0.21} & \cellcolor{gray!6}{1.02} & \cellcolor{gray!6}{2.91} & \cellcolor{gray!6}{5.02} & \cellcolor{gray!6}{6.80}\\
Import price index & -0.01 & -0.09 & -0.11 & -0.58 & -0.75 & -0.83 & -0.92\\
\cellcolor{gray!6}{Gross nominal wage} & \cellcolor{gray!6}{0.00} & \cellcolor{gray!6}{0.10} & \cellcolor{gray!6}{0.27} & \cellcolor{gray!6}{1.03} & \cellcolor{gray!6}{3.32} & \cellcolor{gray!6}{6.26} & \cellcolor{gray!6}{8.92}\\
Real cost of labor & 0.07 & 0.08 & 0.07 & 0.79 & 0.44 & -0.19 & -0.81\\
\cellcolor{gray!6}{Wage employment rate (in thousands)} & \cellcolor{gray!6}{0.70} & \cellcolor{gray!6}{3.82} & \cellcolor{gray!6}{4.29} & \cellcolor{gray!6}{34.47} & \cellcolor{gray!6}{63.39} & \cellcolor{gray!6}{82.96} & \cellcolor{gray!6}{97.35}\\
Unemployment rate (in point) & -0.01 & -0.06 & -0.06 & -0.50 & -0.87 & -1.11 & -1.29\\
\cellcolor{gray!6}{Trade balance (in point of GDP)} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{0.15} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{1.17} & \cellcolor{gray!6}{1.89} & \cellcolor{gray!6}{2.12} & \cellcolor{gray!6}{2.07}\\
Public budget balance (in points of GDP) & 0.01 & 0.12 & 0.20 & 0.88 & 1.56 & 2.04 & 2.23\\
\cellcolor{gray!6}{Public debt (in points of GDP)} & \cellcolor{gray!6}{-0.05} & \cellcolor{gray!6}{-0.49} & \cellcolor{gray!6}{-1.25} & \cellcolor{gray!6}{-4.81} & \cellcolor{gray!6}{-10.69} & \cellcolor{gray!6}{-17.51} & \cellcolor{gray!6}{-24.33}\\
CO2 emissions & -0.61 & -2.00 & -2.90 & -16.79 & -29.06 & -36.98 & -42.22\\
\bottomrule
\end{tabu}
\end{table}

Tableau subvention sans redistribution

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-17}Macroeconomic impacts of Carbon tax scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
\cellcolor{gray!6}{GDP in volume} & \cellcolor{gray!6}{-0.01} & \cellcolor{gray!6}{-1.55} & \cellcolor{gray!6}{-2.07} & \cellcolor{gray!6}{-1.80} & \cellcolor{gray!6}{-1.49} & \cellcolor{gray!6}{-1.27} & \cellcolor{gray!6}{-1.05}\\
Household consumption & -0.33 & -3.36 & -3.55 & -2.29 & -1.37 & -0.87 & -0.56\\
\cellcolor{gray!6}{Investment} & \cellcolor{gray!6}{0.03} & \cellcolor{gray!6}{-2.26} & \cellcolor{gray!6}{-3.26} & \cellcolor{gray!6}{-2.28} & \cellcolor{gray!6}{-1.11} & \cellcolor{gray!6}{-0.07} & \cellcolor{gray!6}{0.76}\\
Exports & -0.03 & -0.69 & -1.77 & -2.38 & -2.54 & -2.43 & -2.20\\
\cellcolor{gray!6}{Imports} & \cellcolor{gray!6}{-0.43} & \cellcolor{gray!6}{-2.89} & \cellcolor{gray!6}{-3.27} & \cellcolor{gray!6}{-2.31} & \cellcolor{gray!6}{-1.38} & \cellcolor{gray!6}{-0.59} & \cellcolor{gray!6}{-0.01}\\
Household disposable income & -0.46 & -3.46 & -3.42 & -2.24 & -1.40 & -0.89 & -0.57\\
\cellcolor{gray!6}{Household consumption price index} & \cellcolor{gray!6}{0.47} & \cellcolor{gray!6}{3.81} & \cellcolor{gray!6}{5.59} & \cellcolor{gray!6}{6.09} & \cellcolor{gray!6}{5.96} & \cellcolor{gray!6}{5.42} & \cellcolor{gray!6}{4.80}\\
production price index & 0.32 & 3.26 & 5.59 & 6.74 & 6.87 & 6.37 & 5.65\\
\cellcolor{gray!6}{Added value price index} & \cellcolor{gray!6}{-0.24} & \cellcolor{gray!6}{1.33} & \cellcolor{gray!6}{4.27} & \cellcolor{gray!6}{6.07} & \cellcolor{gray!6}{6.55} & \cellcolor{gray!6}{6.35} & \cellcolor{gray!6}{5.83}\\
Intermediate consumption price index & 0.92 & 5.35 & 7.03 & 7.42 & 7.14 & 6.31 & 5.37\\
\cellcolor{gray!6}{Export price index} & \cellcolor{gray!6}{0.50} & \cellcolor{gray!6}{3.26} & \cellcolor{gray!6}{4.76} & \cellcolor{gray!6}{5.05} & \cellcolor{gray!6}{4.84} & \cellcolor{gray!6}{4.35} & \cellcolor{gray!6}{3.79}\\
Import price index & -0.05 & -1.23 & -1.17 & -0.77 & -0.44 & -0.28 & -0.18\\
\cellcolor{gray!6}{Gross nominal wage} & \cellcolor{gray!6}{0.00} & \cellcolor{gray!6}{1.24} & \cellcolor{gray!6}{3.85} & \cellcolor{gray!6}{5.12} & \cellcolor{gray!6}{5.42} & \cellcolor{gray!6}{5.14} & \cellcolor{gray!6}{4.62}\\
Real cost of labor & 0.24 & -0.10 & -0.41 & -0.90 & -1.07 & -1.14 & -1.16\\
\cellcolor{gray!6}{Wage employment rate (in thousands)} & \cellcolor{gray!6}{0.48} & \cellcolor{gray!6}{-47.82} & \cellcolor{gray!6}{-105.45} & \cellcolor{gray!6}{-97.93} & \cellcolor{gray!6}{-75.67} & \cellcolor{gray!6}{-53.80} & \cellcolor{gray!6}{-33.19}\\
Unemployment rate (in point) & -0.01 & 0.78 & 1.51 & 1.33 & 1.00 & 0.70 & 0.42\\
\cellcolor{gray!6}{Trade balance (in point of GDP)} & \cellcolor{gray!6}{0.52} & \cellcolor{gray!6}{3.96} & \cellcolor{gray!6}{4.40} & \cellcolor{gray!6}{3.26} & \cellcolor{gray!6}{2.30} & \cellcolor{gray!6}{1.57} & \cellcolor{gray!6}{1.05}\\
Public budget balance (in points of GDP) & 0.74 & 3.40 & 3.52 & 2.93 & 2.28 & 1.60 & 1.10\\
\cellcolor{gray!6}{Public debt (in points of GDP)} & \cellcolor{gray!6}{-1.06} & \cellcolor{gray!6}{-12.42} & \cellcolor{gray!6}{-25.84} & \cellcolor{gray!6}{-34.39} & \cellcolor{gray!6}{-38.06} & \cellcolor{gray!6}{-38.88} & \cellcolor{gray!6}{-37.84}\\
CO2 emissions & -3.77 & -18.69 & -22.82 & -22.05 & -18.90 & -14.62 & -10.56\\
\bottomrule
\end{tabu}
\end{table}

Tableau subvention avec redistribution

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-18}Macroeconomic impacts of Carbon tax scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
\cellcolor{gray!6}{GDP in volume} & \cellcolor{gray!6}{0.17} & \cellcolor{gray!6}{0.56} & \cellcolor{gray!6}{0.32} & \cellcolor{gray!6}{0.13} & \cellcolor{gray!6}{0.06} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{-0.03}\\
Household consumption & -0.02 & 0.06 & 0.10 & 0.39 & 0.63 & 0.72 & 0.68\\
\cellcolor{gray!6}{Investment} & \cellcolor{gray!6}{0.16} & \cellcolor{gray!6}{-0.19} & \cellcolor{gray!6}{-0.49} & \cellcolor{gray!6}{0.20} & \cellcolor{gray!6}{1.01} & \cellcolor{gray!6}{1.68} & \cellcolor{gray!6}{2.10}\\
Exports & 0.00 & -0.22 & -0.94 & -1.58 & -1.85 & -1.84 & -1.71\\
\cellcolor{gray!6}{Imports} & \cellcolor{gray!6}{-0.30} & \cellcolor{gray!6}{-1.22} & \cellcolor{gray!6}{-1.34} & \cellcolor{gray!6}{-0.86} & \cellcolor{gray!6}{-0.28} & \cellcolor{gray!6}{0.27} & \cellcolor{gray!6}{0.65}\\
Household disposable income & -0.01 & 0.05 & 0.09 & 0.40 & 0.62 & 0.71 & 0.68\\
\cellcolor{gray!6}{Household consumption price index} & \cellcolor{gray!6}{0.27} & \cellcolor{gray!6}{2.13} & \cellcolor{gray!6}{3.88} & \cellcolor{gray!6}{4.59} & \cellcolor{gray!6}{4.62} & \cellcolor{gray!6}{4.25} & \cellcolor{gray!6}{3.81}\\
production price index & 0.08 & 1.15 & 3.23 & 4.70 & 5.11 & 4.87 & 4.40\\
\cellcolor{gray!6}{Added value price index} & \cellcolor{gray!6}{-0.55} & \cellcolor{gray!6}{-1.47} & \cellcolor{gray!6}{1.17} & \cellcolor{gray!6}{3.48} & \cellcolor{gray!6}{4.35} & \cellcolor{gray!6}{4.50} & \cellcolor{gray!6}{4.31}\\
Intermediate consumption price index & 0.76 & 3.93 & 5.47 & 6.02 & 5.89 & 5.22 & 4.46\\
\cellcolor{gray!6}{Export price index} & \cellcolor{gray!6}{0.36} & \cellcolor{gray!6}{1.89} & \cellcolor{gray!6}{3.15} & \cellcolor{gray!6}{3.70} & \cellcolor{gray!6}{3.69} & \cellcolor{gray!6}{3.37} & \cellcolor{gray!6}{2.98}\\
Import price index & -0.05 & -1.19 & -1.11 & -0.73 & -0.42 & -0.27 & -0.18\\
\cellcolor{gray!6}{Gross nominal wage} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.71} & \cellcolor{gray!6}{2.64} & \cellcolor{gray!6}{3.95} & \cellcolor{gray!6}{4.35} & \cellcolor{gray!6}{4.18} & \cellcolor{gray!6}{3.79}\\
Real cost of labor & 0.56 & 2.19 & 1.43 & 0.43 & -0.03 & -0.33 & -0.53\\
\cellcolor{gray!6}{Wage employment rate (in thousands)} & \cellcolor{gray!6}{3.76} & \cellcolor{gray!6}{20.06} & \cellcolor{gray!6}{-1.32} & \cellcolor{gray!6}{-12.88} & \cellcolor{gray!6}{-8.61} & \cellcolor{gray!6}{1.33} & \cellcolor{gray!6}{10.74}\\
Unemployment rate (in point) & -0.07 & -0.30 & 0.04 & 0.18 & 0.11 & -0.03 & -0.15\\
\cellcolor{gray!6}{Trade balance (in point of GDP)} & \cellcolor{gray!6}{0.39} & \cellcolor{gray!6}{2.57} & \cellcolor{gray!6}{2.99} & \cellcolor{gray!6}{2.31} & \cellcolor{gray!6}{1.60} & \cellcolor{gray!6}{1.03} & \cellcolor{gray!6}{0.65}\\
Public budget balance (in points of GDP) & 0.24 & 1.83 & 2.41 & 2.08 & 1.61 & 1.11 & 0.73\\
\cellcolor{gray!6}{Public debt (in points of GDP)} & \cellcolor{gray!6}{-0.50} & \cellcolor{gray!6}{-6.41} & \cellcolor{gray!6}{-15.82} & \cellcolor{gray!6}{-22.39} & \cellcolor{gray!6}{-25.38} & \cellcolor{gray!6}{-26.20} & \cellcolor{gray!6}{-25.56}\\
CO2 emissions & -3.63 & -17.01 & -20.74 & -20.34 & -17.53 & -13.49 & -9.66\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{carbon-tax-1}{%
\subsection{Carbon tax}\label{carbon-tax-1}}

As the carbon tax before 2030 stays at a moderate level, the impacts of
this policy are therefore limited, while the significant effects are
observed during the later period from 2030 to 2050 when a much stronger
tax carbon is implemented. The macroeconomic impacts are summarized in
table 1, the results are expressed as percentage deviation from Baseline
scenario.

Generally speaking, the policy of carbon tax with redistribution of
government revenue has a positive impact on Tunisia's economy. Whereas
GDP increases slightly up to 0.13\% with respect to baseline on 2030,
the relatively rapid augmentation is observed from 2030 to 2050. At the
horizon of 2050, it reaches a highest level (+1.93\%) thanks to the
carbon tax policy. In the meantime, social welfare is improved with the
same rhythme as GDP growth, with a higher consumption level (+4.20\%)
and a higher disposable income (+4.17\%) on 2050.

An intuitive influence of carbon tax is that the price of internal
market will raise, which is in line with our model output: higher
household consumption price of 9.49\% with 11.33\% and 13.14\% for
production price and intermediate consumption price, respectively. The
increasing cost of household and company will force them to choose the
substitution with less CO2 emissions, thus reducing their cost. The
variation of internal price also has an impact on the competitiveness of
local goods on international market, causing a recession for exportation
and a boost for importation.

It is interesting to note that the implemented policy can alleviate
social poverty to some extent. We observed, for example, the continuous
growth of wage employment. It will then reinforce the acceptability of
the climate policy.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-19-1} \end{center}

Along with the economical growth, we find that the emissions reduction
of 42.2\% by 2050 is achieved, then we are now interested in its
pathway. To do this, we firstly employ our extended Kaya identity to
clarify the main driving forces, where, a priori, Economic activities
are expected to have positive effects on emissions, whilst Energy
intensity and Carbon intensity should have negative effects. Figure X.
presents the results of all the aggregated driving forces. We observe
that economy structure has a significantly positive and growing impact
until 2043 where it reaches the peak raising 7947.48 Kt CO2 (+19,38\%)
with regard to baseline, then it begins to decline to 5650,17 Kt CO2
(+12,46\%) on 2050. On the other hand, carbon intensity and energy
intensity show the negative and monotone trend, the former reducing
7128.35 Kt CO2 (-13.77\%) on 2050 and 30715.93 Kt CO2 (-47.18\%) for the
later. However, the influence of economic activities is negligible
(+886,37 Kt CO2 \& +1.86\%), revealing that even though the total
production remains relatively invariable, the revolution of economy
structure and production methods could still strongly impact the
emissions pathway.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-20-1} \end{center}

So how do these driving forces work exactly to impact emissions? To
answer this question, we conduct a sectorial analysis with the help of
our extended Kaya identity. Fig.X depicts the evolution of economy
structure for different sectors. Electricity sector has a positive
impact while energy transformation has a negative one, with all other
sectors staying relatively stable. It indicates the development of
electricity production, and recession of another, standing for the
substitution of electricity over fossil fuels. Compared with fossil
fuels, electricity is potentially less pollutant because it is the final
conversion of renewable energies.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-21-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-22-1} \end{center}

The carbon tax induces the increasing investment for all sectors except
energy transformation, firstly to accelerate the penetration of
renewable energies in electricity mix and secondly, to reduce the
consumption of fossil fuels especially for energy intensive sectors. We
observe then the improvement of energy efficiency, in another word
reduction of energy intensity, for all the sectors of Tunisia's economy,
especially for electricity and industry \& agriculture (Fig.x). However,
the other sectors display slight reduction of energy intensity. For
example, the transportation sector consume majorly jet fuel for aircraft
and diesel for container ship. Electrification faces still huge
challenges for long distance transportation. The inertia of energy
demand thus exists in such a sector despite of the increasing cost for
carbon dioxide emission.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-23-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-24-1} \end{center}

Fig.x shows how energy consumption varies with the carbon tax, which can
be explained by improvement of energy intensity. As what we discussed
above, we can find more and more diminished energy demand for all the
economic sectors and for household. And one more time, we observe the
inertia for transportation and services. Even though there is not
noticeable amelioration of energy intensity for energy transformation,
the overall shrinkage of the sector explains the energy demand profile.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-25-1} \end{center}

The energy intensity represents the choice of production technology
considering whether it is energy intensive or not, whilst the carbon
intensity describes how carbon tax leads the economy to choose the types
of energy. We notice a moderate fall for industry \& agriculture and
energy transformation, meaning the transition towards energies with less
emission. The electricity mix is exogenous according to our modelling
assumptions, that is why the carbon tax has no effect on it, whereas it
might be wildly influenced by climate policies in the real situation. It
is worthy to mention here that energy consumption by household are
almost from energy transformation sector, so we integrated household
energy consumption into energy transformation sector. In fact, the
reduction of carbon intensity observed here in energy transformation
sector is arose by a different energy mix of household rather than the
sector itself.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-26-1} \end{center}

As the carbon tax induces the production of green electricity (with less
pollution per unit of energy production), the energy consumers then have
a more environmental friendly alternative other than fuel. Even though
maybe they are not intended to care about the climate change, using this
alternative enables them to cut back their costs. Therefore, we see the
rapid shifting from fossil fuel to electricity for industry \&
agriculture and the household, and reaching nearly a half of their
energy consumption until 2050 like depicted in Fig.X to X. For industry
\& agriculture, electricity mainly offsets a part of natural gas demand,
which hints the electrification of heating unit for instance. As for
household, the wild spread of electrical or hybrid cars reduces the
domand for fossil fuel.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-27-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-28-1} \end{center}

\hypertarget{energy-subsidies-removal}{%
\subsection{Energy subsidies removal}\label{energy-subsidies-removal}}

In 2024, there is no more energy subsidy, including for electricity. In
contrast to the carbon tax, the long-term effects of a short shock on
energy prices can be observed. The energy subsidies removal with
redistribution has a positive impact on Tunisian GDP in the short and
medium term (+0.56\% in 2025 and +0.32\%), before entering a phase of
diminishing marginal effect (+0.06\% in 2040 and -0.03\% in 2050). The
policy reduces public debt. Thanks to the redistribution, the household
disposable income doesn't decrease, but raises. The main macroeconomic
impacts of energy subsidies removal with redistribution are discussed in
the section ``Importance of redistribution''.

The removal of energy subsidies has little impact on the split in final
consumption between fossil fuels and electricity. The share of
electricity remains relatively stable (29\% of final consumption in 2050
in the scenario with shock) compared to the Baseline scenario (30\% of
final consumption in 2050) as shown in Figure X. Nevertheless, the share
between transport fuels, fuels for other uses and gas is modified by the
policy. The share of gas and transport fuels (respectively 26\% and 29\%
of final energy consumption) increases compared to the baseline scenario
(respectively 24\% and 26\% of final energy consumption). The share of
fuel dedicated to other uses decreases from 21\% of final consumption to
16\% in the scenario with removal of subsidies.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-29-1} \end{center}

CO2 emissions decrease drastically in the short and medium term, before
converging to the emission levels of the Baseline scenario. The
extension of Kaya identity is used to break down the decline in
emissions. Since the electricity mix is exogenous to the ThreeMe model
and the part of electricty in total final energy consumption is stable,
the carbon intensity does not contribute much to the decrease in
emissions as shown in the fig.~X. It is the decrease in energy intensity
(-23\% in 2025, -27\% in 2030 and -12\% in 2050 compared to the Baseline
scenario) that contributes most to the decrease in emissions. If we
break down the contribution of energy intensity to the changes in
emissions by sector (Fig. X), we notice that the energy intensity of the
transport sector does not change compared to the baseline scenario. The
two sectors with the highest contribution of energy intensity to
emission reductions are the electricity sector (-17\% in 2025, -18\% in
2030 and -9\% in 2050 and compared to the Baseline scenario) and the
industry and agriculture sector (-6\% in 2025, -7\% in 2030 and -3\% in
2050 compared to the Baseline scenario).

\begin{center}\includegraphics{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-30-1} \end{center}

The decrease in energy intensity is confirmed by the decrease in energy
consumption (see Fig. X). Indeed, households and all sectors see their
consumption decrease (-19\% for households, -18\% for the electricity
sector, -16\% for the energy transformation sector and -14\% for
industry and agriculture in 2025 compared to the Baseline scenario).
Only the consumption of the transport sector is relatively rigid, which
means that in this sector, the potential for energy efficiency
improvements or capital use changes is relatively lower.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-31-1} \end{center}

We analyse the energy indices for households, as we have data on
consumer prices (see Fig. X). The price of fuels for other use increases
by 207\% in 2030, but the deviation from the Baseline scenario narrows
to +67\% in 2050. The decrease in energy consumption seen above is a
reaction to rising prices. We use a simple formula for the short-term
price elasticity of energy demand \(E_{E/P}\). The latter is the ratio
of the rate of change in demand and the rate of change in price, with
\(D_S\) the energy consumption with shock, \(D_B\) the energy
consumption in the Baseline scenario, \(P_S\) the energy price with
shock and \(D_B\) the energy price in the Baseline scenario.
\[ E_{E/P} \, = \,  \frac{\frac{D_S - D_B}{D_B}}{\frac{P_S - P_B}{P_B}} \]

As we saw in the section ``Importance of redistribution'', the energy
subsidies removal has a positive impact on households' disposable
income, which is small in the short and medium term. In the long term,
households' disposable income increases by 0.68\% in 2050 compared to
the Baseline scenario. A linear regression confirms the existence of a
positive income elasticity, but weak compared to the price elasticity.
We therefore neglect the income elasticity of energy demand. The price
elasticity of demand is equal to -0.54 in 2021, to -0.33 in 2030 and to
-0.44 in 2050. The demand for fuel for other purposes becomes
increasingly rigid in the medium term, before becoming relatively more
elastic in the long term.

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-32}Price elasticity of demand for fuel dedicated to other use}
\centering
\fontsize{7}{9}\selectfont
\begin{tabular}[t]{rr}
\toprule
\textbf{Year} & \textbf{Price elasticity}\\
\midrule
2021 & -0.54\\
2025 & -0.47\\
2030 & -0.33\\
2035 & -0.37\\
2040 & -0.41\\
2045 & -0.46\\
2050 & -0.44\\
\bottomrule
\end{tabular}
\end{table}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-33-1} \end{center}

In the short and medium term, rising energy prices lead to a relative
decrease in energy intensity and in the price elasticity of energy
demand. On the one hand, some of this decrease corresponds to the
capital use adjustment channel \autocites[ ]{finn2000}[
]{gamtessa2018a}. Companies respond to high energy costs by selecting
the most energy-efficient capital available, resulting in reduced energy
consumption and underutilisation of capital. On the other hand, in the
long run, some of the decrease in energy intensity corresponds to
additional investment and energy efficiency improvement. This reaction
implies an increase in capital productivity. Indeed, investment in
industry and agriculture is always higher than in the baseline scenario
(+6.6\% in 2050, see fig.~X). In the long run, the interaction between
these different channels leads to a convergence of post-shock energy
consumption towards the levels of the Baseline scenario. This long-term
increase in energy consumption is explained either by the readjustment
of capital use or by a direct rebound effect.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-34-1} \end{center}

\hypertarget{renewable-energy-scenario}{%
\subsection{Renewable energy scenario}\label{renewable-energy-scenario}}

In this section, we are interested in the impacts of renewable energy
penetration into electricity mix. The main macroeconomic indicators are
presented in the table below. Differently from carbon tax and energy
subsidies, the penetration of renewable energy does not perturb prices
in the market. The increasing GPD ( +2.96\% on 2050 with respect to
baseline ) is mainly derived from prosperity of electricity generation
sector, where the relative variation to baseline scenario is up to
+478.7\% by the horizon 2050. The rapid development of electricity
sector brings also the abundance of working opportunities ( +103k on
2050 with respect to baseline ), arising then the household disposable
income to 3.47\% compared with null policy scenario. In fact, the
electricity is the only sector which is significantly touched by this
policy in terms of either economy or energy (Fig.x and x). As there is
no other economic levers to incite energetic transition, the boom of
economy can be understood as the growing productivity with much less
energetic constrains.

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-35}Macroeconomic impacts of Renewable energy scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
GDP in volume & 0.09 & 0.49 & 1.33 & 1.78 & 2.36 & 2.77 & 2.96\\
Household consumption & 0.05 & 0.40 & 1.59 & 2.03 & 2.61 & 3.14 & 3.48\\
Investment & -0.02 & 0.32 & 1.98 & 3.16 & 4.25 & 4.71 & 4.64\\
Exports & 0.00 & -0.05 & -0.12 & -0.18 & -0.24 & -0.27 & -0.22\\
Imports & -0.12 & -0.32 & 0.27 & 0.45 & 0.60 & 0.76 & 0.86\\
Household disposable income & 0.05 & 0.46 & 1.56 & 2.01 & 2.62 & 3.12 & 3.47\\
Household consumption price index & 0.03 & 0.23 & 0.26 & 0.37 & 0.45 & 0.43 & 0.22\\
production price index & 0.01 & -0.02 & -0.05 & 0.20 & 0.38 & 0.40 & 0.17\\
Added value price index & 0.06 & 0.48 & 0.66 & 0.83 & 0.98 & 1.04 & 0.84\\
Intermediate consumption price index & -0.04 & -0.50 & -0.81 & -0.57 & -0.45 & -0.52 & -0.81\\
Export price index & 0.01 & 0.10 & 0.20 & 0.30 & 0.38 & 0.39 & 0.24\\
Import price index & -0.02 & -0.39 & -0.40 & -0.37 & -0.35 & -0.38 & -0.43\\
Gross nominal wage & 0.06 & 0.51 & 1.17 & 1.51 & 1.94 & 2.21 & 2.28\\
Real cost of labor & -0.01 & -0.06 & 0.35 & 0.48 & 0.70 & 0.89 & 1.15\\
Wage employment rate (in thousands) & 0.68 & 9.23 & 40.89 & 59.02 & 79.82 & 95.15 & 103.17\\
Unemployment rate (in point) & -0.01 & -0.15 & -0.59 & -0.82 & -1.09 & -1.27 & -1.36\\
Trade balance (in point of GDP) & 0.09 & 0.59 & 0.39 & 0.31 & 0.27 & 0.20 & 0.12\\
Public budget balance (in points of GDP) & 0.04 & 0.39 & 0.61 & 0.55 & 0.53 & 0.47 & 0.34\\
Public debt (in points of GDP) & -0.15 & -1.48 & -4.19 & -5.91 & -7.04 & -7.88 & -8.26\\
CO2 emissions & -1.77 & -7.56 & -9.85 & -13.71 & -19.23 & -24.57 & -29.24\\
\bottomrule
\end{tabu}
\end{table}

When it comes to the environmental sphere ( seeing Fig.x ), electricity
sector is the only one with negative impact on emissions profile, it
compensates the positive impacts arose from all other sectors, resulting
in a emissions reduction up to 29.24\% by the end of 2050. Fig.x depicts
the evolution of different driving forces to emissions, where we find
such a emissions reduction is totally thanks to the amelioration of
energy intensity while economic structure and carbon intensity
contribute in another way to CO2 emissions.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-36-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-37-1} \end{center}

The renewable energies policy prompts the rapid development of
electricity sector, but at the same time constrains that of energy
transformation sector as shown in the Fig.x. Such a policy will give
rise to a supply-side structural revolution of energy sector in Tunisia.
More and more investment will be incited into green energy exploitation,
then reduce the cost to exploit renewable energies, making it
increasingly profitable and engendering a growing share of green
electricity in the grid. On the other hand, the fossil fuels lose its
competitiveness compared to renewable electricity due to the shrinkage
of innovation (seeing Fig.x).

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-38-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-39-1} \end{center}

In fact, the expanding investment not only cuts back the cost of
exploitation, but also boosts the energy efficiency in electricity
sector. We notice from Fig.x that electricity is the only sector where
there is a reduction of energy intensity. This is quite intuitive for
the emerging renewable energies replace the fossil fuels in electricity
mix, meaning a stronger independence to fossil fuels, thus less
emissions during electricity generation.

As discussed above that the electricity is the only sector who is
impacted by this policy, the penetration of renewable energies could
seldom influence other sectors. We observe then a rebound effect for
certain sectors. Apparently the renewable energy does not induce the
innovation oriented to improve energy efficiency, and on the other hand,
the fact knowing that electricity is a much more environmental friendly
energy, makes them somehow indifferent to consume more or less energies.
That is to say, the penetration just provides an alternative with less
environmental impacts, rather than intrinsically resolves the problem
meaning a transition from energy-intensive to energy-efficient
production. Thus, in terms of sustainable development, the renewable
energies policy should better cooperate with other economic levers in
order to guarantee its efficiency in the longer term.

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-40-1} \end{center}

\hypertarget{national-low-carbon-strategy-scenario}{%
\subsection{National Low-Carbon Strategy
scenario}\label{national-low-carbon-strategy-scenario}}

Table.X :Macroeconomic impacts of Nation Low-Carbon Strategy scenario in
\% deviation to Baseline

\begin{table}

\caption{\label{tab:unnamed-chunk-41}Macroeconomic impacts of Nation Low-Carbon Strategy scenario in percent deviation to Baseline}
\centering
\fontsize{7}{9}\selectfont
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
\textbf{ } & \textbf{2021} & \textbf{2025} & \textbf{2030} & \textbf{2035} & \textbf{2040} & \textbf{2045} & \textbf{2050}\\
\midrule
\cellcolor{gray!6}{GDP in volume} & \cellcolor{gray!6}{0.2895441} & \cellcolor{gray!6}{1.0705537} & \cellcolor{gray!6}{1.4754452} & \cellcolor{gray!6}{2.2329688} & \cellcolor{gray!6}{3.2564027} & \cellcolor{gray!6}{4.0405452} & \cellcolor{gray!6}{4.4202832}\\
Household consumption & 0.0425383 & 0.5695008 & 1.6247787 & 2.9249813 & 4.6566972 & 6.3542381 & 7.5193048\\
\cellcolor{gray!6}{Investment} & \cellcolor{gray!6}{0.1673353} & \cellcolor{gray!6}{0.2530047} & \cellcolor{gray!6}{1.2685695} & \cellcolor{gray!6}{3.5054685} & \cellcolor{gray!6}{6.2093074} & \cellcolor{gray!6}{8.5473511} & \cellcolor{gray!6}{10.1235641}\\
Exports & -0.0090497 & -0.3028144 & -1.1455957 & -2.0079317 & -2.9337775 & -3.8146015 & -4.4436990\\
\cellcolor{gray!6}{Imports} & \cellcolor{gray!6}{-0.4373043} & \cellcolor{gray!6}{-1.4084930} & \cellcolor{gray!6}{-0.9897993} & \cellcolor{gray!6}{-0.4721709} & \cellcolor{gray!6}{0.3701086} & \cellcolor{gray!6}{1.5979977} & \cellcolor{gray!6}{2.7574615}\\
Household disposable income & 0.0724309 & 0.6145608 & 1.5751917 & 2.9474429 & 4.6701336 & 6.3203368 & 7.4677296\\
\cellcolor{gray!6}{Household consumption price index} & \cellcolor{gray!6}{0.3491234} & \cellcolor{gray!6}{2.4543029} & \cellcolor{gray!6}{4.3315690} & \cellcolor{gray!6}{6.2104482} & \cellcolor{gray!6}{8.3779250} & \cellcolor{gray!6}{10.1570316} & \cellcolor{gray!6}{11.1556452}\\
production price index & 0.1165305 & 1.2914328 & 3.5239563 & 6.3159517 & 9.3252865 & 11.8483263 & 13.3435815\\
\cellcolor{gray!6}{Added value price index} & \cellcolor{gray!6}{-0.5410510} & \cellcolor{gray!6}{-0.8164001} & \cellcolor{gray!6}{2.1806175} & \cellcolor{gray!6}{4.8639822} & \cellcolor{gray!6}{8.2400611} & \cellcolor{gray!6}{11.5332058} & \cellcolor{gray!6}{13.8310490}\\
Intermediate consumption price index & 0.8293088 & 3.6224162 & 5.0064762 & 7.8869342 & 10.4088850 & 11.9558878 & 12.4581399\\
\cellcolor{gray!6}{Export price index} & \cellcolor{gray!6}{0.3739608} & \cellcolor{gray!6}{2.0882720} & \cellcolor{gray!6}{3.5462861} & \cellcolor{gray!6}{4.7573507} & \cellcolor{gray!6}{6.2955455} & \cellcolor{gray!6}{7.6910483} & \cellcolor{gray!6}{8.5298162}\\
Import price index & -0.0654869 & -1.5521032 & -1.4701156 & -1.3765071 & -1.2171764 & -1.2018409 & -1.2769303\\
\cellcolor{gray!6}{Gross nominal wage} & \cellcolor{gray!6}{0.0709812} & \cellcolor{gray!6}{1.2726063} & \cellcolor{gray!6}{3.8734043} & \cellcolor{gray!6}{6.0153625} & \cellcolor{gray!6}{8.6700144} & \cellcolor{gray!6}{11.2843480} & \cellcolor{gray!6}{13.1440481}\\
Real cost of labor & 0.5981838 & 2.0023850 & 1.4908104 & 0.9029344 & 0.1527675 & -0.4981665 & -0.8960226\\
\cellcolor{gray!6}{Wage employment rate (in thousands)} & \cellcolor{gray!6}{5.0681210} & \cellcolor{gray!6}{32.4426680} & \cellcolor{gray!6}{36.6216410} & \cellcolor{gray!6}{64.7511930} & \cellcolor{gray!6}{120.7904060} & \cellcolor{gray!6}{171.1933780} & \cellcolor{gray!6}{205.1478420}\\
Unemployment rate (in point) & -0.0911077 & -0.4931664 & -0.5022689 & -0.9208871 & -1.6635391 & -2.2932214 & -2.7079677\\
\cellcolor{gray!6}{Trade balance (in point of GDP)} & \cellcolor{gray!6}{0.4971976} & \cellcolor{gray!6}{3.0668058} & \cellcolor{gray!6}{3.3011851} & \cellcolor{gray!6}{3.0623372} & \cellcolor{gray!6}{2.8266725} & \cellcolor{gray!6}{2.4749490} & \cellcolor{gray!6}{2.0802386}\\
Public budget balance (in points of GDP) & 0.2922667 & 2.1793959 & 2.9218029 & 2.8943793 & 2.9793966 & 2.9114401 & 2.6638663\\
\cellcolor{gray!6}{Public debt (in points of GDP)} & \cellcolor{gray!6}{-0.6898930} & \cellcolor{gray!6}{-7.9032253} & \cellcolor{gray!6}{-19.4900558} & \cellcolor{gray!6}{-28.7260264} & \cellcolor{gray!6}{-35.8115175} & \cellcolor{gray!6}{-42.0496607} & \cellcolor{gray!6}{-47.2895509}\\
CO2 emissions & -5.8695307 & -24.2395123 & -29.9364314 & -40.7728631 & -51.3816196 & -59.6475800 & -66.0955818\\
\bottomrule
\end{tabu}
\end{table}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-42-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-43-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-44-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-45-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-46-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-47-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-48-1} \end{center}

\begin{center}\includegraphics[width=0.7\linewidth,height=0.7\textheight]{Modele-ThreeMe-Tunisie_Sequeira_Valilou_Wang_files/figure-latex/unnamed-chunk-49-1} \end{center}

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

\hypertarget{lamuxe9lioration-du-cadre-statistique}{%
\subsection{L'amélioration du cadre
statistique}\label{lamuxe9lioration-du-cadre-statistique}}

OUverture : pb du secteur informel non pris en compte par la
comptabilité nationale

\printbibliography[title=Bibliography]

\end{document}
